### ISSUE TITLE
Some new Slash commands

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/edd-slack#56]
- [x] /edd version

- returns current EDD version
- ~~second argument can be a number and can actually change the version of EDD to that number (i.e. `/edd version 2.1.5` would change what's on the site to that version~~

- /edd pending

- could pass `payments`, `vendors`, `comments`, `reviews` and possibly more as a second argument and get back a list of URLs (or maybe buttons) for any of those items in a pending state, otherwise a message stating no pending items found

- ~~/edd info~~
- ~~gets a systeminfo.txt file from the EDD tools~~

- [x] /edd customer {email or ID}
- returns detailed info about a customer matching that email address if they exist. Including other email addresses, URL to their customer page in the admin, # of total purchases, total value of all purchases, etc.

- ~~/edd reset~~
- ~~https://cloudup.com/cLRu-ITGqYF this section in tools has a few functions which can be manually run. Why not create slash commands for running them? Something like `/edd reset store` and _maybe_ with response buttons asking for confirmation.~~
- [x] /edd discount
- Second argument would be discount code
- if it already exists, return a brief report on it
- if it does not, create it and also accept a third argument which is a number like 10 for $10 or 10% for....10%
- we could maybe accept other arguments but I'd suggest making it crazy simple to start. Just the code and the amount.

These are just a few ideas. Not all are required. Let's explore and also think of other ideas.

Also, I am going to bed.

**Comment by d4mation** [comment]
@brashrebel I just noticed some potential issues with `/edd version <version>`:

1. We'd ideally be downloading from the WordPress.org Repo. The .org Repo auto-downloads and extracts to `easy-digital-downloads` which may not match everyone's configuration. Thankfully, EDD mostly solves this for us with `EDD_PLUGIN_DIR`.
2. After we download the `.zip` for the plugin, EDD will effectively be force-disabled as it is being replaced by the chosen version. This _may_ cause problems with Slack while it is attempting to process the replacement. This I'd need to confirm though.

I'm going to proceed with it and give it a shot. I think that instead of accepting a `<version>` parameter though I'm going to instead have it be a "boolean" where the phrase `change` is included to change it then a dropdown will appear like the in the link @BigActual posted. This will help ensure that valid input is provided for the version number.

**Comment by brashrebel** [comment]
@d4mation if you really wanted to, you could hard code in some options. Like just major releases. Or the last patch release before every major release. Or arrange it in some way so that it parses the numbers x.x.x which should always be there....I think. Just ideas. I trust your judgement.

**Comment by d4mation** [comment]
An update on `/edd version <version>`:

I have it set to be `/edd version change` and it then shows a Dropdown of options. The code for this works... locally. It however does not on our WP Engine test install (Since this is some SSL-only functionality, so I cannot fully test it locally).

I have not been able to figure out quite why. It appears to be a permissions issue, but I'm using all the same methods as WP Core for updating plugins. Unless WP Engine is looking for that to occur at certain Action Hooks and denying any other code from running ZIP Extraction tasks I've got nothing.

It creates all necessary folders as it is extracting, but it only extracts a single file if we're lucky. The error spat out is always related to being unable to write the main plugin file `easy-digital-downloads/easy-digital-downloads.php`

If we had another SSL-enabled server to test on I could rule out whether it was WP Engine killing it or not. 

Anyway, this should be the primary blocker for v1.1 at this point. While I haven't started the other Slash Commands above, I would figure they should be much easier to implement than `/edd version change` has been so far 😛 

Each other Issue for v1.1 has been labeled as `done` and I've merged them into `release/v1.1`

**Comment by brashrebel** [comment]
This sounds pretty involved. I'm thinking we should punt to 1.2. I can also setup an SSL dev site on A2  at least if you want.

**Comment by d4mation** [comment]
Sounds good. Let's punt `/edd version change` to v1.2. I'll make an Issue for it and move that code over so I don't lose it (Since like I said, it does seem to work at least locally).

**Comment by d4mation** [comment]
`/edd discount RBMGETSITFREEWOO` (An existing discount)
![image](https://user-images.githubusercontent.com/7770631/29190806-736ae38e-7de9-11e7-8bc3-8fab237dc1bc.png)

`/edd discount NEWDISCOUNTDOLLAR $10` (This is a new discount for $10 off. The Currency Symbol does not matter. The code only checks for a Percent sign. The help text shows the appropriate currency symbol for the settings on their Store)
![image](https://user-images.githubusercontent.com/7770631/29190893-bf4a677a-7de9-11e7-84bc-572c0afa6e41.png)

`/edd discount NEWDISCOUNTPERCENT 10%` (This is a new discount for 10% off)
![image](https://user-images.githubusercontent.com/7770631/29190923-dbc0baee-7de9-11e7-9cba-00a558495574.png)

`/edd discount NOTFOUND` (This Discount Code does not exist)
![image](https://user-images.githubusercontent.com/7770631/29190830-8e1498e2-7de9-11e7-865c-58dc99fb5035.png)

`/edd help discount`
![image](https://user-images.githubusercontent.com/7770631/29190851-9cd16a36-7de9-11e7-86a0-a9457f5e78b6.png)

**Comment by brashrebel** [comment]
So as I understand it, setting the third parameter changes this from retrieving to creating? Like if you set a price this _makes_ a discount code instead of looking for a match?

**Comment by d4mation** [comment]
Precisely.

I realized though I need to add a condition so that if the third parameter is set on an existing Discount Code that it updates it, so I'm quickly adding that now.

**Comment by brashrebel** [comment]
It might be a good idea to make this distinction between reading and creating in the help command and documentation. It wasn't obvious in your example. But I like how simple it is. This is way cool.

**Comment by d4mation** [comment]
Updating an existing Discount Code by setting an Amount
`/edd discount RBMGETSITFREEWOO 100%`
![image](https://user-images.githubusercontent.com/7770631/29212972-2f8ee238-7e6f-11e7-9408-749f3efa6d01.png)

Revised `/edd help discount`
![image](https://user-images.githubusercontent.com/7770631/29213164-10d2edd4-7e70-11e7-807a-59b3390ee60f.png)

**Comment by d4mation** [comment]
Since the `EDD_Customer` object does not care at all whether you throw a Customer ID or an Email Address at it, `/edd customer` was super quick!

I used IDs for most of my testing (quicker to type), but I did check Email Addresses too and those work just fine. This would be a neat feature for people with Notifications set up for Purchases and such because if they have an `%email%` merge tag in there, they could grab their Email and look up some quick info on that Customer from directly in Slack :+1:

Successful retrieval of a Customer: `/edd customer 1`
![image](https://user-images.githubusercontent.com/7770631/29225343-e684443e-7e9b-11e7-8d03-b1c81bab4846.png)

No Customer Found: `/edd customer 9001`
![image](https://user-images.githubusercontent.com/7770631/29225318-cd8c634e-7e9b-11e7-9369-552be992b9f2.png)

`/edd help customer`
For the Email Address example, it grabs the Admin Email if one exists within `wp_options`. Otherwise, it falls back to `fakeemail@fake.dev`, but I don't foresee that happening 😛 
![image](https://user-images.githubusercontent.com/7770631/29225437-4627ad4a-7e9c-11e7-80e8-48a6bb85d2bd.png)

For `/edd customer` I utilized different Fields for the Message Attachment which I really, really liked. I'm going to re-configure the other Slash Commands to use these also where applicable.

**Comment by brashrebel** [comment]
This is looking so nice ❤️

**Comment by d4mation** [comment]
Went ahead and gave `/edd sales` and `/edd discount` the same facelift ❤️ 

`/edd version` still uses the old way, but given its utility it makes more sense that way. It only reports back one bit of information rather than multiple.

![image](https://user-images.githubusercontent.com/7770631/29228492-e51f3610-7ea7-11e7-8e6f-0d9d4cea2c98.png)

![image](https://user-images.githubusercontent.com/7770631/29228477-dbf970d2-7ea7-11e7-8356-be8edc730c3d.png)

**Comment by d4mation** [comment]
> /edd pending
> could pass payments, vendors, COMMENTS, reviews and possibly more as a second argument and get back a list of URLs (or maybe buttons) for any of those items in a pending state, otherwise a message stating no pending items found

Just to be sure, I figure these should be narrowed down to only Comments on Downloads?

And for Reviews, should those be limited to just "regular" Download Reviews, or also include Vendor Feedback (Technically part of EDD Reviews) if FES is active?

I figure ideally I should also "wall off" things like Comments or Reviews if they don't apply to the Install, similarly to how the Triggers work. No sense in making Comments an option for `/edd pending` if they aren't enabled for Downloads.

**Comment by brashrebel** [comment]
Thinking real quick here, I think first that yes, the standard across all EDD extensions is that anything that is an integration with another extension should be conditionally included and nested inside the `integrations` directory.

As for the `/pending` command...I'm not sure about this one. Starting to think it could be complicated and might be better to punt. There could be a lot of debate about all the different types of data which can have statuses including pending (vendors, downloads, payments, comments, reviews, vendor submissions, commissions(?), etc.) so maybe we should break this out into its own issue. The idea is to empower a Slack user to take actions from within Slack if they want to and approving/declining things that are pending could be useful. But there are so many different things that we'll need to keep in mind. I vote new issue and punt.

**Comment by d4mation** [comment]
Ah, yes, my intent was to conditionally include bits of `/edd pending` as appropriate when different integrations were active. Although with you explicitly mentioning the `/integrations/` directory... I'm thinking I should have `/edd pending`'s output use Filters/Actions up the wazoo in order to facilitate like the rest of the Plugin rather than just throwing a bunch of conditional statements in its callback function like what was initially in mind.

I'll make a new Issue and punt. With that though, I think that finishes out everything that was marked for v1.1 :tada:
