### ISSUE TITLE
Undefined index: price_id - Purchase Limit integration

### ISSUE THREAD

**Issue by SDavisMedia** [realbigplugins/edd-slack#72]
```
Notice: Undefined index: price_id in /Applications/MAMP/htdocs/edd/wp-content/plugins/edd-slack/core/integrations/edd-purchase-limit/class-edd-slack-purchase-limit.php on line 106

Notice: Undefined index: price_id in /Applications/MAMP/htdocs/edd/wp-content/plugins/edd-slack/core/integrations/edd-purchase-limit/class-edd-slack-purchase-limit.php on line 123
```

--

These notices appear while trying to save a manually created subscription (Recurring Payments).

**Comment by d4mation** [comment]
If you re-pull `release/v1.1`, this should be set :+1: 

Turns out it was caused by a function I was using from Purchase Limits expecting `null` as the Price ID parameter and in the event of a Download without Variable Pricing, the `price_id` Index was not set. I just set it to set it with `null` if it did not exist which appears to handle it.

**Comment by SDavisMedia** [comment]
Yup. All good now. :+1:
