### ISSUE TITLE
Field labels should be above fields, not below

### ISSUE THREAD

**Issue by pippinsplugins** [realbigplugins/edd-slack#78]
When adding notifications, the label for the input field is currently positioned below the input fields. This is confusing as it results in the labels appearing they are actually for the field below them.

Labels should go above inputs, descriptions should go below.
<img width="938" alt="screen shot 2017-07-19 at 3 50 55 pm" src="https://user-images.githubusercontent.com/1034109/28388991-1074550e-6c9a-11e7-92d8-a5a5edff4f09.png">

**Comment by d4mation** [comment]
I agree with you here and it took me a little bit to remember why I did it this way.

I'm using the `desc`, `tooltip_title`, and `tooltip_desc` fields for the Settings API to generate those Field Labels as the Settings API itself expects any Field Labels to be on the left side of the screen rather than directly adjacent to the Field.

I'll just have to use different Indices in the `$args` Array and generate the Labels myself above the Fields.

This change should also apply to EDD Fields as they output their Modals the same way.

**Comment by d4mation** [comment]
Moved :+1:

![image](https://user-images.githubusercontent.com/7770631/28429791-f2faa390-6d4b-11e7-8d3a-aa9d1bb4825d.png)

**Comment by brashrebel** [comment]
Confirmed done.
